"""add trust_score

Revision ID: 7d9bab5241d6
Revises: 959e360ef765
Create Date: 2025-11-16 09:36:41.157518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9bab5241d6'
down_revision: Union[str, Sequence[str], None] = '959e360ef765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('trust_score_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'trust_score_data')
    # ### end Alembic commands ###
