"""Create assessment table

Revision ID: d14dec3f21b1
Revises: 
Create Date: 2025-11-15 13:32:11.706489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14dec3f21b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('input_name', sa.String(length=255), nullable=False),
    sa.Column('input_vendor_name', sa.String(length=255), nullable=False),
    sa.Column('input_url', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='assessmenttype'), nullable=False),
    sa.Column('assessment_status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='assessmentstatus'), nullable=False),
    sa.Column('entity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_input_name'), 'assessments', ['input_name'], unique=False)
    op.create_index(op.f('ix_assessments_input_vendor_name'), 'assessments', ['input_vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_input_vendor_name'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_input_name'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
