"""fix typing

Revision ID: f4001f49040e
Revises: d14dec3f21b1
Create Date: 2025-11-15 16:09:17.607759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4001f49040e'
down_revision: Union[str, Sequence[str], None] = 'd14dec3f21b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'input_vendor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_assessments_input_vendor_name'), table_name='assessments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assessments_input_vendor_name'), 'assessments', ['input_vendor_name'], unique=False)
    op.alter_column('assessments', 'input_vendor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
